### ISSUE TITLE
Support for Mp3 and photos

### ISSUE THREAD

**Issue by frodo76** [ddurdle/KODI-Box#1]
Hi Team, I am trying to use Durdle_0.1.0 and do not see my music file via kodi. I also please wanted to ask if support for photos might be added?. I am using Kodi version 14 Git: ad747d9., Ubuntu 14.04.1 LTS.

**Comment by ddurdle** [comment]
music added in 0.1.1+, photo support to be added soon.

**Comment by ddurdle** [comment]
music/audio support - http://dmdsoftware.net/repository.ddurdle/plugin.video.box-0.1.2.zip

**Comment by frodo76** [comment]
Thank you!
Date: Thu, 10 Sep 2015 16:41:03 -0700
