### ISSUE TITLE
I can access my account , but no music files are showing

### ISSUE THREAD

**Issue by zer04c** [ddurdle/KODI-Box#2]
It seems like it's connecting okay, and I get reports from box that access has gone through. I can browse correctly through the folders but non of the music files are showing.

**Comment by ddurdle** [comment]
now in testing in 0.1.1, audio playback is working now when tested

**Comment by zer04c** [comment]
Great I'll download and test as well.

**Comment by zer04c** [comment]
I can see the files now , awesome. The list caps out at 20 items for some reason.

**Comment by ddurdle** [comment]
I'll look into the cap on file listings tonight.

I'm planning on devoting time for this plugin, including implementing using
the API.

**Comment by zer04c** [comment]
Works great apart from that , thanks for sharing your work.

**Comment by ddurdle** [comment]
Actually I spotted the issue and a 0.1.2 is being pushed out to address the
20 limit

**Comment by ddurdle** [comment]
Should be fixed in 0.1.2 http://dmdsoftware.net/repository.ddurdle/plugin.video.box-0.1.2.zip

**Comment by zer04c** [comment]
Nice, yeah that works, thanks.

**Comment by ddurdle** [comment]
Don't hesitate to drop in some suggestions for features.

**Comment by zer04c** [comment]
Thanks , it all works great. You can play whole folders which is nice , the only thing I can't do on my Kodi is add files to a playlist , but not sure if that's possible from within the app or not ?
